apiVersion: v1
kind: "Service"
metadata:
  name: alertmanager
  labels:
    name: alertmanager
  namespace: ops
spec:
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
  selector:
    app: alertmanager
