---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtk-php-cms-server-new
  namespace: default
  labels:
    app.kubernetes.io/name: dtk-php-cms-server-new
    app.kubernetes.io/business: platform
    app.kubernetes.io/runtime: php
    app.kubernetes.io/tier: backend
    app.kubernetes.io/environment: prod
    app.kubernetes.io/managed-by: yong.xd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dtk-php-cms-server-new
      app.kubernetes.io/business: platform
      app.kubernetes.io/runtime: php
      app.kubernetes.io/tier: backend
      app.kubernetes.io/environment: prod
      app.kubernetes.io/managed-by: yong.xd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dtk-php-cms-server-new
        app.kubernetes.io/business: platform
        app.kubernetes.io/runtime: php
        app.kubernetes.io/tier: backend
        app.kubernetes.io/environment: prod
        app.kubernetes.io/managed-by: yong.xd
      annotations:
        configmap/checksum: "96ff75e8d9becc33de899087f05053ebec0fb00fffdb6435049bcabea95d6321"
    spec:
      imagePullSecrets:
        - name: aliyun-regcred
      serviceAccountName: default
      securityContext:
      containers:
        - name: nginx
          securityContext:
          image: "registryw-ngx:latest"
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 200m
          lifecycle:
            preStop:
              exec:
                command:
                  # Gracefully shutdown
                  - /usr/local/openresty/bin/openresty
                  - -s
                  - quit
        - name: php-fpm
          image: "registry-vpc.cn-beserver_new-fpm:latest"
          # 此处由于目录需要写入权限，而直接挂载目录权限是只读，所以单个文件挂载
          volumeMounts:
          - name: static-json
            mountPath: /app/dtk_static_cms_server_new/build/www/dist/asset-manifest.json
            subPath: asset-manifest.json
          - name: static-json2
            mountPath: /app/dtk_static_cms_server_new/build/www/static.json
            subPath: static.json
          - name: config
            mountPath: /app/protected/config/console.php
            subPath: console.php
          - name: config
            mountPath: /app/protected/config/database.php
            subPath: database.php
          - name: config
            mountPath: /app/protected/config/main.php
            subPath: main.php
          - name: config
            mountPath: /app/protected/config/test.php
            subPath: test.php
          - name: runtime
            mountPath: /app/protected/runtime
          ports:
            - name: php-fpm
              containerPort: 9000
              protocol: TCP
          env:
          - name: WORKER_NUM
            value: "100"
          livenessProbe:
            tcpSocket:
              port: 9000
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: 9000
            periodSeconds: 10
            timeoutSeconds: 3
          securityContext:
            capabilities:
              add:
              - SYS_PTRACE
          lifecycle:
            preStop:
              exec:
                command: [
                  # Gracefully shutdown php-fpm
                  "sleep", "10"
                ]
          resources:
            requests:
              cpu: 1000m
              memory: 2048Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
      volumes:
      - name: config
        configMap:
          name: dtk-php-cms-server-new-config
      - name: nginx-config
        configMap:
          name: dtk-php-cms-server-new-nginx-config
      - name: static-json
        configMap:
          name: dtk-php-cms-server-new-static-json
      - name: static-json2
        configMap:
          name: dtk-static-cms-server-new-static-json
      - name: runtime
        emptyDir: {}
