---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dtk-php-cms-server-new
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: dtk-php-cms-server-new
  targetCPUUtilizationPercentage: 60
