apiVersion: v1
kind: Service
metadata:
  name: dtk-php-cms-server-new
  namespace: default
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-force-override-listeners: "true"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: lb-2zeqy18
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-scheduler: "wrr"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 12000
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: dtk-php-cms-server-new
    app.kubernetes.io/business: platform
    app.kubernetes.io/runtime: php
    app.kubernetes.io/tier: backend
    app.kubernetes.io/environment: prod
    app.kubernetes.io/managed-by: yong.xd