apiVersion: v1
kind: PersistentVolume
metadata:
  name: okvoice-task-logs-1
spec:
  capacity:
    storage: 512Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-1
  nfs:
    path: /
    server: 95f6049d05-ptp39.cn-zhangjiakou.nas.aliyuncs.com
  mountOptions:
  - nfsvers=4.0

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: okvoice-task-logs-1
  namespace: master-okvoice-task
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Gi
  storageClassName: nfs-1
#  volumeName: logs
