apiVersion: v1
kind: PersistentVolume
metadata:
  name: fast-jenkins
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: v1
  nfs:
    path: /share/jenkins
    server: 09703033-qw3t.cn-zhangjiakou.extreme.nas.aliyuncs.com
  mountOptions:
  - vers=3
  - nolock,tcp,noresvport

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-jenkins
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: v1
  volumeName: fast-jenkins
