apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-publish-logs-1
spec:
  capacity:
    storage: 512Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-1
  nfs:
    path: /
    server: 9c1ff49169-jtl75.cn-zhangjiakou.nas.aliyuncs.com
  mountOptions:
  - nfsvers=4.0

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-publish-logs-1
  namespace: task-publish
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Gi
  storageClassName: nfs-1
#  volumeName: logs
