apiVersion: v1
kind: PersistentVolume
metadata:
  name: m2
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: v1
  hostPath:
    path: /nfs/m2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: m2
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: v1
  volumeName: m2

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-workspaces
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: v1
  hostPath:
    path: /nfs/jenkins/jenkins/workspaces

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-workspaces
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: v1
  volumeName: jenkins-workspaces
