apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        hosts {
            192.168.12.16 dataoke.com
            192.168.23.57 openapi.dataoke.com

            fallthrough
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {

          pods verified
          fallthrough in-addr.arpa ip6.arpa
        }
        autopath @kubernetes
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
