# 定义coredns配置文件，绑定A记录等

apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        hosts {
            # 定义内部A记录
            192.168.12.16 itgod.org
            192.168.23.57 test.com

            fallthrough
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {

          pods verified
          fallthrough in-addr.arpa ip6.arpa
        }
        autopath @kubernetes
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
