apiVersion: v1
kind: Namespace
metadata:
  name: okvoice-shop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: okvoice-shop-logs-1
spec:
  capacity:
    storage: 512Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-1
  nfs:
    path: /
    server: 930a94bf52-gwe78.cn-zhangjiakou.nas.aliyuncs.com
  mountOptions:
  - nfsvers=4.0

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: okvoice-shop-logs-1
  namespace: okvoice-shop
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Gi
  storageClassName: nfs-1
#  volumeName: logs
