---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtk-java-neighbor-live
  namespace: default
  labels:
    app.kubernetes.io/name: neighbor-live
    app.kubernetes.io/runtime: java
    app.kubernetes.io/tier: backend
    app.kubernetes.io/environment: prod
    app.kubernetes.io/managed-by: yong.xd
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: neighbor-live
      app.kubernetes.io/runtime: java
      app.kubernetes.io/tier: backend
      app.kubernetes.io/environment: prod
      app.kubernetes.io/managed-by: yong.xd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: neighbor-live
        app.kubernetes.io/runtime: java
        app.kubernetes.io/tier: backend
        app.kubernetes.io/environment: prod
        app.kubernetes.io/managed-by: yong.xd
      annotations:
        configmap/checksum: "96ff75e8d9becc33de899087f05053ebec0fb00fffdb6435049bcabea95d6321"
    spec:
      imagePullSecrets:
        - name: aliyun-regcred
      serviceAccountName: default
      securityContext:
      containers:
        - name: spring-boot
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          image: "registry:latest"
          env:
          - name: JAVA_OPTIONS
            value: "-XX:+UseContainerSupport -XX:+MaxRAMPercentage=75.0 -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -Duser.timezone=GMT+8"
          command:
          - java
          - "-server"
          - -jar
          - app.jar
          - --spring.profiles.active=prod
          - --spring.config.location=application-yaml.yaml
          volumeMounts:
          - name: config
            mountPath: /opt/app/application-yaml.yaml
            subPath: application-yaml.yaml
          - name: log
            mountPath: /var/log/nginx/java/
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/live/health
              port: 9742
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /api/live/health
              port: 9742
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 1000m
              memory: 2048Mi
            limits:
              cpu: 2000m
              memory: 4096Mi
      volumes:
      - name: config
        configMap:
          name: dtk-java-neighbor-live-config
      - name: log
        emptyDir: {}