---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dtk-java-neighbor-live
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: dtk-java-neighbor-live
  targetCPUUtilizationPercentage: 70
