apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: ops
data:
  grafana.ini: |
    [server]
    domain = monitors.haojiequ.com
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
    serve_from_sub_path = true