apiVersion: v1
kind: "Service"
metadata:
  name: grafana
  labels:
    name: grafana
  namespace: ops
spec:
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: grafana