apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ops
data:
  legacy.json: |
    [
      {
    "targets": [
    "dtk_cms_php6_H:19999",
    "dtk_cralwer2:9537"
     ]
     }
     ]

  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - path_prefix: "/alertmanager/"
          static_configs:
            - targets: ['alertmanager.ops:9093']
    rule_files:
      - /etc/prometheus/rules/*.rules
    scrape_configs:
      - job_name: 'prometheus'
        metrics_path: "/prometheus/metrics"
        static_configs:
        - targets: ['localhost:9090']

      - job_name: 'legacy'
        file_sd_configs:
          - files:
            - /etc/prometheus/legacy.json
            refresh_interval: 10s
      - job_name: http_response_body
        params:
          module:
          - http_response_body
        metrics_path: /probe
        static_configs:
        - targets:
          - https://beibei.dataoke.com/api/recommend/recommendItems?user_id=700777&category=1
          labels:
            monitoring: beibei
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox.ops.svc.cluster.local:9115
      - job_name: http2xx_probe
        params:
          module:
          - http_2xx
          target:
          - https://dataoke.com
        metrics_path: /probe
        static_configs:
        - targets:
          - https://openapi.dataoke.com/api/goods/get-goods-list?appKey=5cc6a75b697eb&cids=1&pageId=1&pageSize=10&sign=2347581E0F8E59C243239DF181D2C90B&version=v1.2.3&
          - http://v2.api.haodanku.com/itemlist/apikey/D5134FF28717/nav/3/cid/0/back/10/min_id/1
          - http://api.tbk.dingdanxia.com/spk/douyin_items&apikey=Ts2wAAFpTFKXrBTC5Rug9DnA2XI6LnYm
          labels:
            monitoring: business
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox.ops.svc.cluster.local:9115
      - job_name: 'kubernetes-kubelet'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics

      - job_name: 'kubernetes-cadvisor'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)

      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
        - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: default;kubernetes;https
        - target_label: __address__
          replacement: kubernetes.default.svc:443

      - job_name: 'kubernetes-pods'
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
        - source_labels: [__meta_pod_template_generation]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
