apiVersion: v1
kind: Namespace
metadata:
  name: quanzi
---
apiVersion: v1
data:
  nginx.conf: |+
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    worker_rlimit_nofile 65535;
    events {
        worker_connections  65535;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        server_tokens off;
        server_names_hash_bucket_size 512;
        client_header_buffer_size 32k;
        large_client_header_buffers 4 32k;
        client_max_body_size 1024m;



         log_format json '{ "access_time": "$time_iso8601", '
            '"remote_addr": "$remote_addr", '
            '"http_referrer": "$http_referer", '
            '"request": "$request", '
            '"status": $status, '
            '"bytes":$body_bytes_sent, '
            '"agent": "$http_user_agent", '
            '"x_forwarded": "$http_x_forwarded_for", '
            '"upstr_addr": "$upstream_addr",'
            '"request_id": "$http_x_request_id",'
            '"ups_resp_time": "$upstream_response_time" }';


        access_log  /var/log/nginx/access.log  json;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }

kind: ConfigMap
metadata:
  name: nginx-base-conf
  namespace: quanzi
---
apiVersion: v1
data:
  app.conf: |+
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    }

kind: ConfigMap
metadata:
  name: nginx-confd-dir
  namespace: quanzi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: quanzi
  namespace: quanzi
spec:
  replicas: 1
  selector:
    matchLabels:
     name: quanzi
  template:
    metadata:
      labels:
        name: quanzi
    spec:
      containers:
      - name: quanzi
        image: 172.26.112.47/quanzi/quanzi:1
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "4096m"
            memory: "4096Mi"
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 3
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-base-conf
          subPath: nginx.conf
        - mountPath: /etc/nginx/conf.d
          name: nginx-confd-dir
      volumes:
      - name: nginx-base-conf
        configMap:
          name: nginx-base-conf
      - name: nginx-confd-dir
        configMap:
          name: nginx-confd-dir
---
apiVersion: v1
kind: Service
metadata:
  name: quanzi
  namespace: quanzi
spec:
  selector:
    name: quanzi
  ports:
  - name: http
    port: 80
    targetPort: 80
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: quanzi
  namespace: quanzi
spec:
  rules:
    - host:
      http:
        paths:
        - path: /
          backend:
            serviceName: quanzi
            servicePort: 80

