apiVersion: v1
kind: Namespace
metadata:
  name: quanzi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: quanzi-logs-1
spec:
  capacity:
    storage: 512Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-1
  nfs:
    path: /
    server: 9df8c4bfaa-acd51.cn-zhangjiakou.nas.aliyuncs.com
  mountOptions:
  - nfsvers=4.0

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quanzi-logs-1
  namespace: quanzi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Gi
  storageClassName: nfs-1
#  volumeName: logs
#
