apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        rewrite name yxd.com itgod.org
        hosts {

        #     1.1.1.2 yxd.com
            fallthrough
        }

        kubernetes cluster.local in-addr.arpa ip6.arpa {
          #upstream 172.18.0.10  ###主coredns
          upstream kube-dns.kube-system.svc.cluster.local.  ###主coredns
          pods verified
          fallthrough in-addr.arpa ip6.arpa
        }

        autopath @kubernetes
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  namespace: test1
  name: coredns继承
