---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns继承
  namespace: test1

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-clusterrole
rules:
  - apiGroups: [""]
    resources: ["services","namespaces","pods","endpoints","nodes"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: example-clusterrole
subjects:
  - kind: ServiceAccount
    name: coredns继承
    namespace: test1
