apiVersion: v1
kind: Namespace
metadata:
  name: master-okvoice-task
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: okvoice-task
  namespace: master-okvoice-task
spec:
  replicas: 1
  selector:
    matchLabels:
     name: okvoice-task
  template:
    metadata:
      labels:
        name: okvoice-task
    spec:
      containers:
      - name: okvoice-task
        image: 172.26.112.47/okvoice-task/okvoice-task:94
        resources:
          requests:
            cpu: "100m"
            memory: "2048Mi"
          limits:
            cpu: "4096m"
            memory: "5128Mi"
#        readinessProbe:
#          tcpSocket:
#            port: 80
#          initialDelaySeconds: 30
#          periodSeconds: 3
#        livenessProbe:
#          tcpSocket:
#            port: 80
#          initialDelaySeconds: 180
#          periodSeconds: 3


---
apiVersion: v1
kind: Service
metadata:
  name: okvoice-task
  namespace: master-okvoice-task
spec:
  selector:
    name: okvoice-task
  ports:
  - name: http
    port: 80
    targetPort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: okvoice-task
  namespace: master-okvoice-task
spec:
  rules:
    - host: master-okvoice-task.local.okyuyin.com
      http:
        paths:
        - path: /
          backend:
            serviceName: okvoice-task
            servicePort: 80
    - host: task.local.okyuyin.com
      http:
        paths:
        - path: /
          backend:
            serviceName: okvoice-task
            servicePort: 80

